_target_: lerobot.common.robot_devices.robots.ros.RosRobot
cameras:
  top:
    _target_: lerobot.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: 4
    fps: 30
    # width: 176 #640
    # height: 144 # 480
    width: 1280
    height: 720
  bottom:
    _target_: lerobot.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: 0
    fps: 30
    # width: 176 # 640
    # height: 144 # 480
    width: 1280
    height: 720

topics:
  observation:
    image:
      top: 
        topic: cam_dev_video4
        msg_type: 'sensor_msgs/Image'
      bottom:
        topic: cam_dev_video0
        msg_type: 'sensor_msgs/Image'
    state: 
      topic: 'my_gen3_lite/base_feedback'
      msg_type: 'kortex_driver/BaseCyclic_Feedback'
  next:
    reward: 
      topic: 'reward'
      msg_type: 'std_msgs/Float32'
      # msg_type: 'std_msgs/Int8'
    success:
      topic: 'success'
      msg_type: 'std_msgs/Bool'
  action:
    topic: 'joy'
    msg_type: 'sensor_msgs/Joy'
    fps: 10
