# @package _global_

fps: 10

env:
  name: robosuite
  task: Stack
  image_size: 84
  state_dim: 32
  action_dim: 7
  fps: ${fps}
  episode_length: 500
  hard_reset: false
  gym:
    obs_type: pixels_agent_pos
    render_mode: rgb_array
    visualization_width: 384
    visualization_height: 384
